version: '3.9'

services:
  backend:
    image: tornado
    build: ./backend/
    ports:
      - "81:81"
    environment:
      - QUEUE_NAME=test1
      - HOST_TO=my-rabbitmq
    restart: always
    depends_on:
        - my-rabbitmq

  my-rabbitmq:
      image: rabbitmq
      build: ./rabbitmq/
      ports:
        - "5672:5672"
        - "15672:15672"

  fastapi:
    build: ./fastapi_consumer/
    ports:
      - "8001:8001"
    environment:
      - HOST_FROM=my-rabbitmq
      - PORT_FROM=5672
      - QUEUE_NAME=test1
      - DATABASE_URL=postgresql://fastapi:fastapi@db:5432/fastapi
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"



